[pytest]
markers =
    authentication: mark test as requiring authentication setup
    mul_cluster: mark test as requiring multi-cluster setup
    access_management: mark test as requiring access management setup
    
filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning
